source 'https://rubygems.org'
ruby '2.3.1'
gem 'rspec'
gem 'sinatra'
gem 'rack'
gem 'rack-test'
gem 'guard'
gem 'guard-rspec'
gem 'foreman'
gem 'pony'
gem 'dotenv'
gem 'pry'
gem "sinatra-cross_origin", "~> 0.3.1"
